name: 'hr-angular-fe'
on: ['push']
jobs:
  build-angular-fe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # - name: Install all needed packages for app
      #   run: npm install --force

      - name: Build angular client
        run: npx nx run hr-angular:build --configuration=production
